AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
 Blecon Example Webhook Handler


Globals:
  Function:
    Timeout: 3

Resources:
  ProcessRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_request/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      FunctionUrlConfig:
        AuthType: NONE


Outputs:
  URLEndpoint:
      Description: "Your Lambda Function URL Endpoint. Set this as the handler in your Blecon Network."
      Value: !GetAtt ProcessRequestFunctionUrl.FunctionUrl